spring:
  application:
    name: vocabuddy-service
eureka:
   client:
      serviceUrl:
         #defaultZone: https://vocabuddy-discovery.herokuapp.com/eureka
        defaultZone: http://localhost:8761/eureka
server:
  port: 8081
